# Generated by Django 4.2.4 on 2023-09-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
